name: "Deployment"

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Authentication.API Deployment
      - name: Build & Push to Docker Hub (Authenticaton.API)
        working-directory: src
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }} -f ./Services/Authentication/Authentication.API/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }}

      # Chat.API Deployment
      - name: Build & Push to Docker Hub (Chat.API)
        working-directory: src
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_CHAT_API_IMAGE_NAME }} -f ./Services/Chat/Chat.API/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_CHAT_API_IMAGE_NAME }}

  azure:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish to Azure App Service (Authentication.API)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_AUTHENTICATION_APP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_AUTHENTICATION_PUBLISHPROFILE }}
          images: index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }}

      - name: Publish to Azure App Service (Chat.API)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_CHAT_APP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_CHAT_PUBLISHPROFILE }}
          images: index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_CHAT_API_IMAGE_NAME }}
