name: Publish Docker Images

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build Docker Images
        working-directory:  src
        run:  docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/socialplatformapp:authentication-api -f ./Services/Authentication/Authentication.API/Dockerfile .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Push Images to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/socialplatformapp:authentication-api
