name: dotnet_cicd_workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore ./src/SocialPlatformApp.sln

      - name: Build Solution
        run: dotnet build ./src/SocialPlatformApp.sln --no-restore

      - name: Run Test Cases
        run: dotnet test ./src/SocialPlatformApp.sln --no-build --verbosity normal

  deployment:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Authentication.API Deployment
      - name: Build Image (Authenticaton.API)
        working-directory: src
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }} -f ./Services/Authentication/Authentication.API/Dockerfile .

      - name: Tag Image (Authenticaton.API)
        run: docker tag ${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }} registry.heroku.cmo/${{ secrets.HEROKU_AUTHENTICATION_API_APP_NAME }}/web

      - name: Push to Docker Hub (Authenticaton.API)
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }}

      - name: Push to Heroku Container Registry (Authenticaton.API)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          heroku container:push -a ${{ secrets.HEROKU_AUTHENTICATION_API_APP_NAME }} web

  publish:
    runs-on: ubuntu-latest
    needs: deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          heroku container:release -a ${{ secrets.HEROKU_AUTHENTICATION_API_APP_NAME }} web

    # environment:
    #   name: "production"
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: "mxah0d1gcu7dce10grwzaf34"
    #     slot-name: "production"
    #     publish-profile: ${{ secrets.AzureAppService_PublishProfile_41318e37f99146ceb1705f3076fb1e84 }}
    #     images: "index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }}"
