name: Build & Test Solution

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build & Test .NET
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore ./src/SocialPlatformApp.sln

      - name: Build Solution
        run: dotnet build ./src/SocialPlatformApp.sln --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Test Cases
        run: dotnet test ./src/SocialPlatformApp.sln --no-build --verbosity normal
