name: dotnet_cicd_workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # dotnet:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v2
  #       with:
  #         dotnet-version: 6.0.x

  #     - name: Restore Dependencies
  #       run: dotnet restore ./src/SocialPlatformApp.sln

  #     - name: Build Solution
  #       run: dotnet build ./src/SocialPlatformApp.sln --no-restore

  #     - name: Run Test Cases
  #       run: dotnet test ./src/SocialPlatformApp.sln --no-build --verbosity normal

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: dotnet

  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Build Images
  #       working-directory: src
  #       run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }} -f ./Services/Authentication/Authentication.API/Dockerfile .

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Push to Docker Hub
  #       run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }}

  heroku:
    runs-on: ubuntu-latest
    # needs: docker

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy Authentication.API
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: "src"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_AUTHENTICATION_API_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true

    # environment:
    #   name: "production"
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: "mxah0d1gcu7dce10grwzaf34"
    #     slot-name: "production"
    #     publish-profile: ${{ secrets.AzureAppService_PublishProfile_41318e37f99146ceb1705f3076fb1e84 }}
    #     images: "index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_AUTHENTICATION_API_IMAGE_NAME }}"
